Updates the Windows image used for unit tests
The current image is deprecated, resulting in failures:

ERROR: (ImageVersionDeprecated) VM Image from publisher: MicrosoftWindowsServer with - Offer: WindowsServer, Sku: 2022-datacenter-smalldisk-g2, Version: 20348.524.220201 is deprecated.

Example: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit-windows-master/1643230608895250432